// Generated by Life section editor. Commit this file to version control.
// These are pixel offsets from the base grid position for desktop moodboard layout.

export interface Position {
  x: number;
  y: number;
  rotate: number;
}

export const lifePositions: Position[] = [
  {
    "x": -209.984375,
    "y": -182.9296875,
    "rotate": -8
  },
  {
    "x": 260.15234375,
    "y": -276.08203125,
    "rotate": -6.757031250000001
  },
  {
    "x": -271.0703125,
    "y": 96.51171875,
    "rotate": 8.044921875
  },
  {
    "x": 160.3125,
    "y": 127.3515625,
    "rotate": -2.6058593750000005
  },
  {
    "x": 72.4921875,
    "y": -206.55078125,
    "rotate": 5.18203125
  },
  {
    "x": -103.0390625,
    "y": 143.7734375,
    "rotate": -10.3015625
  },
  {
    "x": 341.4453125,
    "y": 81.7265625,
    "rotate": 5.679296875
  }
];
