// Generated by Life section editor. Commit this file to version control.
// These are pixel offsets from the base grid position for desktop moodboard layout.

export interface Position {
  x: number;
  y: number;
  rotate: number;
}

export const lifePositions: Position[] = [
  {
    "x": -241.50390625,
    "y": -164.74609375,
    "rotate": -8
  },
  {
    "x": 263.64453125,
    "y": -279.140625,
    "rotate": -6.1578125
  },
  {
    "x": -143.5546875,
    "y": 110.484375,
    "rotate": 12
  },
  {
    "x": 202.859375,
    "y": 132.91015625,
    "rotate": -6
  },
  {
    "x": 101.75390625,
    "y": -174.86328125,
    "rotate": 3
  },
  {
    "x": -5.09765625,
    "y": 176.55078125,
    "rotate": -10
  },
  {
    "x": 359.0546875,
    "y": 57.2265625,
    "rotate": 7
  },
  {
    "x": -321.55078125,
    "y": 85.60546875,
    "rotate": -4
  },
  {
    "x": -36.63671875,
    "y": -256.11328125,
    "rotate": -18.135546875
  }
];
